- .gitignore
- buildspec.yml
- adds aws build spec to push content to S3 bucket
- adds storybook-static folder to git ignore
> S3 Bucket POC

- source/patterns/components/card/card.stories.jsx
- source/patterns/components/card/card.twig
- source/patterns/components/featured-card/featured-card-article.yml
- source/patterns/components/featured-card/featured-card.css
- source/patterns/components/featured-card/featured-card.stories.jsx
- source/patterns/components/featured-card/featured-card.twig
- source/patterns/components/featured-card/featured-card.yml
- Creates the Featured Card component for use in the Article/Event Highlight component (coming soon)
- Minor updates to the card component by removing the CSS import as this is no longer needed since all css styles are available in Storybook atomatically.
> WIP-2166: Featured card

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
- source/patterns/collections/content-highlight/content-highlight.stories.jsx
- Fix eslint error
- Add theme switcher
> add theme switcher, fix eslint error

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- source/patterns/intro.mdx
> disable docs by default

- .storybook/decorators.jsx
- source/patterns/components/callout/callout.css
- source/patterns/components/callout/callout.stories.jsx
- source/patterns/components/callout/callout.twig
- source/patterns/components/callout/callout.yml
- source/patterns/elements/title/title.twig
- surface.libraries.yml
- Migrates the Callout component to storybook
- Creates the Callout stories for the various variations
- Adds background color decorators.
> WIP-2171: Callout component

- source/patterns/collections/person-directory/person-directory.css
- source/patterns/collections/person-directory/person-directory.stories.jsx
- source/patterns/collections/person-directory/person-directory.twig
- source/patterns/collections/person-directory/person-directory.yml
- source/patterns/components/callout/callout.css
- source/patterns/components/person-card/person-card.css
- source/patterns/components/person-card/person-card.stories.jsx
- source/patterns/components/person-card/person-card.twig
- source/patterns/components/person-card/person-card.yml
- source/patterns/elements/date/date.css
- surface.libraries.yml
- Creates the Person Card & Person Directory components and stories.
- Creates Grid and List variations for person directory displays.
- Adds background colors
> WIP-2180: Person Card & Person Directory

- source/patterns/components/callout/callout.twig
- source/patterns/components/event-card/event-card.css
- source/patterns/components/event-card/event-card.stories.jsx
- source/patterns/components/event-card/event-card.twig
- source/patterns/components/event-card/event-card.yml
- surface.libraries.yml
- Migrates event card component from patternlab to storybook.
- Updates logic for inheriting modifier and attributes on some components.
> WIP-2181: Event card

- source/patterns/components/call-to-action/call-to-action.css
- source/patterns/components/call-to-action/call-to-action.stories.jsx
- source/patterns/components/call-to-action/call-to-action.twig
- source/patterns/components/call-to-action/call-to-action.yml
- surface.libraries.yml
- Adds Call to action component and stories.
- Adds stories variations with background colors.
> WIP-2183  call to action

- .eslintrc.yml
- .prettierrc.yml
- .storybook/main.js
- .storybook/preview.js
- .stylelintrc.yml
- package-lock.json
- package.json
- source/base/props/animations.css
- source/base/props/fonts.css
- source/patterns/collections/content-highlight/content-highlight.css
- source/patterns/components/callout/callout.stories.jsx
- source/patterns/components/card/card.css
- source/patterns/components/featured-card/featured-card.css
- source/patterns/elements/button/button.css
- source/patterns/elements/date-badge/date-badge.css
- source/patterns/elements/date-badge/date-badge.stories.jsx
- vite.config.js
- Removes Prettier
- adds additional config
> Storybook standards

- source/patterns/collections/person-listing/person-listing.css
- source/patterns/collections/person-listing/person-listing.stories.jsx
- source/patterns/collections/person-listing/person-listing.twig
- source/patterns/collections/person-listing/person-listing.yml
- Creates person listing component.
> WIP-2183: Person listing

- README.md
- Adds basic README to document specifics about the Surface theme and how to use it, build, and run it.
> (Chaz, could you please update the readme) WIP-2163: Adds README

- source/patterns/elements/site-logo/site-logo.css
- source/patterns/elements/site-logo/site-logo.stories.jsx
- source/patterns/elements/site-logo/site-logo.twig
- source/patterns/elements/site-logo/site-logo.yml
- source/patterns/layouts/site-footer/site-footer.stories.jsx
- source/patterns/layouts/site-footer/site-footer.twig
- source/patterns/styles.css
- Fixes issue with site-footer styles not being automatically applied by adding the path to layouts to `styles.css`.
- Removes import of `site-footer.css` in site-footer story.
- Minor updates to footer logo spacing.
> WIP-2193: Site footer fixes

- source/patterns/components/metric/metric.css
- source/patterns/components/metric/metric.stories.jsx
- source/patterns/components/metric/metric.twig
- source/patterns/components/metric/metric.yml
- source/patterns/components/search-results/search-results.css
- source/patterns/components/search-results/search-results.stories.jsx
- source/patterns/components/search-results/search-results.twig
- source/patterns/components/search-results/search-results.yml
- surface.libraries.yml
- Adds the Metric component and stories including variations with background colors.
- Adds Search results component and story.
- Adds Drupal libraries for both.
> WIP-2193: Metric & Search results

- .storybook/manager.js
- source/patterns/components/menu-sidebar/menu-sidebar-toggle.css
- source/patterns/components/menu-sidebar/menu-sidebar.css
- source/patterns/components/menu-sidebar/menu-sidebar.js
- source/patterns/components/menu-sidebar/menu-sidebar.stories.jsx
- source/patterns/components/menu-sidebar/menu-sidebar.twig
- source/patterns/components/menu-sidebar/menu-sidebar.yml
- source/patterns/components/menu-sidebar/menu.twig
- source/patterns/components/share/share.css
- source/patterns/components/share/share.stories.jsx
- source/patterns/components/share/share.twig
- source/patterns/scripts.js
- surface.libraries.yml
- Adds menu sidebar component and story.
- Adds formerly `sidebar-toggle.css` to the menu-sidebar directory and renamed it `menu-sidebar-toggle.css`.
- Adds Share component and story.
> WIP-2193: Menu sidebar

- package-lock.json
- package.json
- source/patterns/components/menu-quicklinks/menu-quicklinks.stories.jsx
- source/patterns/components/menu-quicklinks/menu-quicklinks.twig
- source/patterns/components/menu-quicklinks/menu-quicklinks.yml
Adds Menu quicklinks story that uses macro twig template.
- Tested in Storybook
- Tested in Drupal
> menu quicklinks

- source/patterns/collections/content-highlight/content-highlight.css
- source/patterns/collections/content-highlight/content-highlight.twig
- source/patterns/collections/content-highlight/images/article-highlight-bottom.svg
- source/patterns/collections/content-highlight/images/article-highlight-top.svg
- source/patterns/collections/content-highlight/images/content-highlight-bottom.svg
- source/patterns/collections/content-highlight/images/content-highlight-top.svg
- source/patterns/components/tabs/tabs.css
- source/patterns/components/tabs/tabs.js
- source/patterns/components/tabs/tabs.stories.jsx
- source/patterns/components/tabs/tabs.twig
- source/patterns/components/tabs/tabs.yml
- source/patterns/components/typewriter/typewriter.css
- source/patterns/components/typewriter/typewriter.js
- source/patterns/components/typewriter/typewriter.stories.jsx
- source/patterns/components/typewriter/typewriter.twig
- source/patterns/components/typewriter/typewriter.yml
- source/patterns/elements/taxonomy-term/taxonomy-term.twig
- source/patterns/elements/taxonomy-term/taxonomy-term.yml
- source/patterns/elements/translate/translate.css
- source/patterns/elements/translate/translate.js
- source/patterns/elements/translate/translate.twig
- source/patterns/scripts.js
- surface.libraries.yml
- Adds the Tabs component and story.
- Adds the Typewriter component and story. JS does not work in Storybook.  This will be addressed at a later time.
- Adds the Translate component.  JS has not been tested.
- Adds Taxonomy term component.
- Updates Content Highlight component based on recent changes to prod.
> WIP-2193: Tabs, Typewriter, Taxonomy term, and Translate

- source/patterns/layouts/block/block.css
- source/patterns/layouts/block/block.twig
- source/patterns/layouts/facet-block/facet-block.css
- source/patterns/layouts/facet-block/facet-block.twig
- source/patterns/layouts/layout-views-grid-horizontal/layout-views-grid-horizontal.css
- source/patterns/layouts/layout-views-grid-vertical/layout-views-grid-vertical.css
- source/patterns/layouts/layout/layout.css
- source/patterns/layouts/page-listing/page-listing.css
- source/patterns/layouts/page-listing/page-listing.twig
- source/patterns/layouts/page/page.css
- source/patterns/layouts/region/region.twig
- source/patterns/layouts/site-container/site-container.twig
- source/patterns/layouts/view-event/view-event.css
- source/patterns/layouts/view-event/view-event.twig
- source/patterns/layouts/view-grid/view-grid.css
- source/patterns/layouts/view-grid/view-grid.twig
- source/patterns/layouts/view-listing/view-listing.css
- source/patterns/layouts/view-listing/view-listing.twig
- source/patterns/layouts/view/view.css
- source/patterns/layouts/view/view.twig
- surface.libraries.yml
Adds the following Layouts components.  NOTE:  Not all items here have or need a Storybook story.  Some of them are simply css styles without markup or data.
- Block
- Event
- Facet-block
- Layout
- Layout-view-grid-horzontal
- Layout-view-grid-vertical
- Page
- Page-listing
- Region
- Site-container
- View
- View-event
- View-grid
- View-listing
> WIP-2211: Layouts

- .storybook/decorators.jsx
- Fixes decorators background color by adding the corresponding background colors custom properties as inline styles.
> WIP-2147: Decorators

- source/patterns/components/card/card.stories.jsx
- source/patterns/components/card/card.yml
- Updates fields for cards variations.
> WIP-2147: Card

- source/patterns/components/video-hero/video-hero.css
- source/patterns/components/video-hero/video-hero.js
- source/patterns/components/video-hero/video-hero.stories.jsx
- source/patterns/components/video-hero/video-hero.twig
- source/patterns/components/video-hero/video-hero.yml
- surface.libraries.yml
- vite.config.js
- Adds the Video hero component and story.
- Makes a modification to the copy task to include mp4s.  This is a temporary change until we figure out a way to place videos on the server differently.
> WIP-2147: Video hero

- source/patterns/elements/forms/demos/checkradio.twig
- source/patterns/elements/forms/demos/color.twig
- source/patterns/elements/forms/demos/fieldset.twig
- source/patterns/elements/forms/demos/file.twig
- source/patterns/elements/forms/demos/forms.stories.jsx
- source/patterns/elements/forms/demos/label.twig
- source/patterns/elements/forms/demos/range.twig
- source/patterns/elements/forms/demos/select.twig
- source/patterns/elements/forms/demos/textarea.twig
- source/patterns/elements/forms/demos/textfields.twig
- source/patterns/elements/forms/input/input.twig
- source/patterns/storybook.css
- surface.libraries.yml
- Adds form elements demos to storybook.  These demo elements automatically inherit any css styles that already exist.
> WIP-2147: Form elements demos

- package-lock.json
- package.json
- postcss.config.js
- Add postcss-nested back to fix nesting compilation issues
> fix nesting

- .storybook/preview-head.html
- source/patterns/collections/flockler-embed/flockler-embed.css
- source/patterns/collections/flockler-embed/flockler-embed.stories.jsx
- source/patterns/collections/flockler-embed/flockler-embed.twig
- source/patterns/collections/flockler-embed/flockler-embed.yml
- Addresses issue with Flockler embed not pulling feed items.  After testing I discovered that Flockler needs a hard-reload of the browser to show the items.
> WIP-2266: Flockler
